### ISSUE TITLE
Feature Request: need better logging in the call method in bot.py.

### ISSUE THREAD

**Issue by LEXmono** [LEXmono/q#60]

**Comment by LEXmono** [comment]
Ran !mars two time consecutively. First time gave the following error:
```
!mars does not exist: Exception
Traceback (most recent call last):
File "/var/task/bot/bot.py", line 159, in q_input
q.handle_command(data, context)
File "/var/task/bot/bot.py", line 80, in handle_command
response = self.call(command, query, user=slack_event['user'])
File "/var/task/bot/bot.py", line 153, in call
raise Exception("
{}
does not exist".format(name))
Exception: !mars does not exist
```
