### ISSUE TITLE
Feature Request: Fix KeyError for !stock

### ISSUE THREAD

**Issue by LEXmono** [LEXmono/q#8]

**Comment by LEXmono** [comment]
'''
'2017-11-24': KeyError
Traceback (most recent call last):
File "/var/task/bot/bot.py", line 113, in q_input
q.handle_command(data, context)
File "/var/task/bot/bot.py", line 72, in handle_command
response = self.call(command, query)
File "/var/task/bot/bot.py", line 104, in call
command = command_map.call(name.lstrip('!'), *args, **kwargs)
File "/var/task/bot/command_map.py", line 76, in call
return command(*args, **kargs)
File "/var/task/bot/commands/stock.py", line 35, in stock
data = request.json()['Time Series (Daily)'][today_date]
KeyError: '2017-11-24'
'''

**Comment by LEXmono** [comment]
Fixed in https://github.com/LEXmono/q/commit/3e23e6333e452d313602d22d50b73efba73134a5
